Fix compilation warning on Elixir 1.11
Here's an example of the warning:
```
==> slack
Compiling 10 files (.ex)
warning: redefining @doc attribute previously set at line 88.

Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head:

    @doc """
    new docs
    """
    def lookup_channel_name(...)

  lib/slack/lookups.ex:95: Slack.Lookups.lookup_channel_name/2

Compilation failed due to warnings while using the --warnings-as-errors option
```

On previous versions the initial `@doc` was silently ignored:
```
iex(1)> h Slack.Lookups.lookup_channel_name

                   def lookup_channel_name(channel_id, slack)

Turns a Slack private channel ID ("G…") into a string in the format
"#CHANNEL_NAME".
```